# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
    ]
